<?php

namespace AppBundle\Repository;

/**
 * Post_TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Post_TagsRepository extends \Doctrine\ORM\EntityRepository
{
}
