# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
 #шифрование пароля..
    encoders:
       AppBundle\Entity\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #указывает провайдера..см презентацию
    providers:
        database_users:
            entity:
                class: AppBundle:User
                property: name

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: database_users
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }