
index:
    path:     /
    defaults: { _controller: AppBundle:Blog:index }

view:
    path:     /view/{id}
    defaults: { _controller: AppBundle:Blog:view }

add:
    path:     /add
    defaults: { _controller: AppBundle:Blog:add }


save:
    path:     /save
    defaults: { _controller: AppBundle:Data:save }

get:
    path:     /get
    defaults: { _controller: AppBundle:Data:get }

login:
    path:     /login
    defaults: { _controller: AppBundle:User:login }

index:
    path:     /index
    defaults: { _controller: AppBundle:Admin:index }


register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }

profile:
    path:     /profile
    defaults: { _controller: AppBundle:User:profile }
    
