AppBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        email:
            type: string
            length: 255
        lastLogin:
            type: string
            length: 255
            column: last_login
    lifecycleCallbacks: {  }
